name: CI

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
    detect-changes:
        runs-on: ubuntu-latest
        outputs:
            backend: ${{ steps.changes.outputs.backend }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Detect changes
              uses: dorny/paths-filter@v2
              id: changes
              with:
                  filters: |
                      backend:
                        - 'phunparty-backend/**'

    backend-checks:
        needs: detect-changes
        if: needs.detect-changes.outputs.backend == 'true'
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:13
                env:
                    POSTGRES_PASSWORD: test_password
                    POSTGRES_USER: test_user
                    POSTGRES_DB: test_phunparty
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
                  cache: "pip"
                  cache-dependency-path: "phunparty-backend/requirements.txt"

            - name: Install dependencies
              run: |
                  cd phunparty-backend
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest pytest-asyncio httpx flake8

            - name: Lint with flake8
              run: |
                  cd phunparty-backend
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

            - name: Run tests
              env:
                  DB_HOST: localhost
                  DB_PORT: 5432
                  DB_USER: test_user
                  DB_PASSWORD: test_password
                  DB_NAME: test_phunparty
                  SECRET_KEY: test_secret_key_for_testing_only
                  ALGORITHM: HS256
                  ACCESS_TOKEN_EXPIRE_MINUTES: 30
              run: |
                  cd phunparty-backend
                  pytest
